function(build_clang)
    if (REMOVE_DEBUG_INFO)
        if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            string(REPLACE "-s" "" CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}")
            string(REPLACE "-s" "" CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
            target_compile_options(${CMAKE_PROJECT_NAME} PRIVATE -Oz)
        endif ()
    endif ()
    if (NOT STRIPPED_VERSION)
        if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -static")
            set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES LINK_FLAGS "-Wl,--subsystem,windows")
        elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -static-libgcc -static-libstdc++ -static -lpthread")
        endif ()
    endif ()
    if (PROFILE_NAME STREQUAL "debug")
        set(CMAKE_BUILD_TYPE Debug)
    else ()
        set(CMAKE_BUILD_TYPE Release)
    endif ()
endfunction()