function(build_gcc)
    if (REMOVE_DEBUG_INFO)
        if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -s")
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -s")
            target_compile_options(${CMAKE_PROJECT_NAME} PRIVATE -Oz)
        endif ()
    endif ()
    if (NOT STRIPPED_VERSION)
        if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -static-libgcc -static-libstdc++ -static")
            target_link_options(${CMAKE_PROJECT_NAME} PRIVATE -static -static-libgcc -static-libstdc++ -Wl,--allow-multiple-definition)
        elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -static-libgcc -static-libstdc++ -static -lpthread")
        endif ()
    endif ()
    if (PROFILE_NAME STREQUAL "debug")
        set(CMAKE_BUILD_TYPE Debug)
    else ()
        set(CMAKE_BUILD_TYPE Release)
        if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
            set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES LINK_FLAGS "-mwindows")
        endif ()
    endif ()
endfunction()
