function(build_msvc)
    if (REMOVE_DEBUG_INFO)
        if (MSVC)
            set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /RTC- /D NDEBUG /DEBUG:NONE")
            set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /RTC- /D NDEBUG /DEBUG:NONE")
            target_compile_options(${CMAKE_PROJECT_NAME} PRIVATE /O2 /GL)
        endif ()
    endif ()
    if (NOT STRIPPED_VERSION)
        if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
            if (MSVC)
                # Static linking for MSVC runtime
                set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
                foreach (flag_var CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
                        CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
                    if (${flag_var} MATCHES "/MD")
                        string(REGEX REPLACE "/MD" "/MT" ${flag_var} "${${flag_var}}")
                    endif ()
                endforeach ()
                target_compile_options(${CMAKE_PROJECT_NAME} PRIVATE /MT) # Ensure static runtime linking
            endif ()
        endif ()
    endif ()
    if (PROFILE_NAME STREQUAL "debug")
        set(CMAKE_BUILD_TYPE Debug)
    else ()
        set(CMAKE_BUILD_TYPE Release)
        if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
            if (MSVC)
                set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES LINK_FLAGS "/SUBSYSTEM:WINDOWS")
            endif ()
        endif ()
    endif ()
endfunction()